// KP HQ delete controls — loaded after app.js so these page renderers extend the live UI.
const delBtn=(table,id,label)=>`<button class="danger mini" onclick="deleteRecord('${table}','${id}','${esc(label)}')">Delete</button>`;
async function deleteRecord(table,id,label){
  if(!confirm(`Delete ${label}?\n\nThis cannot be undone.`)) return;
  const {error}=await sb.from(table).delete().eq('id',id);
  if(error){alert(`Could not delete ${label}: ${error.message}`);return;}
  await loadAll(); page();
}
function dashboard(v){let inc=D.transactions.filter(x=>x.type==='Income').reduce((a,x)=>a+ +x.amount,0),out=D.transactions.filter(x=>x.type==='Expense').reduce((a,x)=>a+ +x.amount,0);v.innerHTML=`<div class="metrics">${[['Clients',D.clients.length],['Active projects',D.projects.filter(x=>!['Complete','Cancelled'].includes(x.status)).length],['Revenue',money(inc)],['Net',money(inc-out)]].map(x=>`<div class="card metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="sectionhead"><div><h2>CEO Action Queue</h2><p>What needs your attention next.</p></div><button class="btn" onclick="modal('task')">+ Task</button></div>${rows(D.tasks,t=>`<div><strong>${esc(t.title)}</strong><span>${esc(t.due_date||'Open')}</span></div><div class="rowactions"><span class="tag">${t.completed?'Done':'Open'}</span>${delBtn('tasks',t.id,t.title)}</div>`)}`}
function clients(v){v.innerHTML=`<div class="sectionhead"><div><h2>Client roster</h2><p>Clients and engagements.</p></div><button class="btn" onclick="modal('client')">+ Client</button></div>${rows(D.clients,c=>`<div><strong>${esc(c.name)}</strong><span>${D.projects.filter(p=>p.client_id===c.id).length} projects • ${esc(c.status)}</span></div><div class="rowactions"><button class="secondary mini" onclick="modal('project','${c.id}')">+ Project</button>${delBtn('clients',c.id,c.name)}</div>`)}`}
function projects(v){v.innerHTML=`<div class="sectionhead"><div><h2>Projects</h2><p>Every active engagement.</p></div><button class="btn" onclick="modal('project')">+ Project</button></div>${rows(D.projects,p=>`<div><span>${esc(D.clients.find(c=>c.id===p.client_id)?.name||'Client')}</span><strong>${esc(p.name)}</strong><span>${esc(p.status)} • ${esc(p.next_action||'No next action')}</span></div><div class="rowactions"><strong>${money(p.value)}</strong>${delBtn('projects',p.id,p.name)}</div>`)}`}
function productions(v){v.innerHTML=`<div class="sectionhead"><div><h2>Productions</h2><p>Dates, crew, cost and margin.</p></div><button class="btn" onclick="modal('production')">+ Production</button></div>${rows(D.productions,p=>`<div><strong>${esc(p.name)}</strong><span>${esc(p.production_date||'Date TBD')} • ${esc(p.crew||'Crew TBD')} • ${esc(p.status)}</span></div><div class="rowactions"><div><strong>${money(p.client_value)}</strong><span>Margin ${money(+p.client_value- +p.production_cost)}</span></div><button class="secondary mini" onclick="modal('editProduction','${p.id}')">Edit</button>${delBtn('productions',p.id,p.name)}</div>`)}`}
function team(v){v.innerHTML=`<div class="sectionhead"><div><h2>Team</h2><p>Contractors and agreements.</p></div><button class="btn" onclick="modal('contractor')">+ Contractor</button></div>${rows(D.contractors,c=>`<div><strong>${esc(c.name)}</strong><span>${esc(c.role||'')} • ${esc(c.email||'')}</span></div><div class="rowactions"><button class="secondary mini" onclick="modal('agreement','${c.id}')">+ Contract</button>${delBtn('contractors',c.id,c.name)}</div>`)}<div class="sectionhead"><div><h2>Contract tracking</h2></div></div>${rows(D.agreements,a=>`<div><strong>${esc(D.contractors.find(c=>c.id===a.contractor_id)?.name||'Contractor')}</strong><span>${esc(D.projects.find(p=>p.id===a.project_id)?.name||'General')} • ${esc(a.rate||'')}</span></div><div class="rowactions"><span class="tag">${esc(a.status)}</span>${delBtn('contractor_agreements',a.id,'this contractor contract')}</div>`)}`}
function documents(v){v.innerHTML=`<div class="sectionhead"><div><h2>Documents & invoicing</h2><p>Create contracts and Stripe-ready invoices.</p></div><div class="actions"><button class="secondary" onclick="modal('document','Contract')">+ Contract</button><button class="btn" onclick="modal('document','Invoice')">+ Invoice</button></div></div>${rows(D.documents,d=>`<div><span>${esc(d.type)}</span><strong>${esc(d.title)}</strong><span>${esc(d.status)}${d.customer_email?' • '+esc(d.customer_email):''}</span></div><div class="rowactions"><strong>${money(d.amount)}</strong>${d.type==='Invoice'?`<button class="pay mini" onclick="stripePay('${d.id}')">${d.payment_url?'Open payment':'Create payment link'}</button>`:''}${delBtn('documents',d.id,d.title)}</div>`)}`}
function finance(v){let i=D.transactions.filter(x=>x.type==='Income').reduce((a,x)=>a+ +x.amount,0),o=D.transactions.filter(x=>x.type==='Expense').reduce((a,x)=>a+ +x.amount,0);v.innerHTML=`<div class="metrics"><div class="card metric"><span>Income</span><strong>${money(i)}</strong></div><div class="card metric"><span>Expenses</span><strong>${money(o)}</strong></div><div class="card metric"><span>Net</span><strong>${money(i-o)}</strong></div></div><div class="sectionhead"><h2>Transactions</h2><button class="btn" onclick="modal('transaction')">+ Transaction</button></div>${rows(D.transactions,t=>`<div><strong>${esc(t.description)}</strong><span>${esc(t.transaction_date||'')} • ${esc(t.type)}</span></div><div class="rowactions"><strong>${money(t.amount)}</strong>${delBtn('transactions',t.id,t.description||'this transaction')}</div>`)}`}
function calendar(v){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),cells='';for(let i=0;i<first;i++)cells+='<div class="day blank"></div>';for(let d=1;d<=days;d++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=D.events.filter(e=>e.event_date===iso),prod=D.productions.filter(p=>p.production_date===iso);cells+=`<div class="day"><b>${d}</b>${ev.map(e=>`<span class="calevent">${esc(e.title)}</span>`).join('')}${prod.map(p=>`<span class="calevent production">${esc(p.name)}</span>`).join('')}</div>`}v.innerHTML=`<div class="sectionhead"><div><h2>${calDate.toLocaleString('default',{month:'long'})} ${y}</h2><p>KP events + production dates.</p></div><div class="actions"><button class="secondary" onclick="moveMonth(-1)">←</button><button class="secondary" onclick="moveMonth(1)">→</button><a class="secondary linkbtn" target="_blank" href="https://calendar.google.com/">Google Calendar ↗</a><button class="btn" onclick="modal('event')">+ Event</button></div></div><div class="calendar"><div class="week">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<b>${x}</b>`).join('')}</div><div class="days">${cells}</div></div><div class="sectionhead"><div><h2>Calendar events</h2><p>Manage events created inside KP HQ.</p></div></div>${rows(D.events,e=>`<div><strong>${esc(e.title)}</strong><span>${esc(e.event_date||'Date TBD')} ${esc(e.event_time||'')} • ${esc(e.type||'Event')}</span></div>${delBtn('calendar_events',e.id,e.title)}`)}<div class="integration"><div><strong>Google Calendar</strong><p>Calendar sync layer is staged. Google OAuth still needs to be authorized before two-way sync is live.</p></div><span class="tag">Setup required</span></div>`}
